language: node_js

sudo: required

node_js:
  - '8'

env:
  global:
    - CXX=g++-4.8
    - CC_TEST_REPORTER_ID=83238dc5069a6d904fe721bad6f2b030e036cb0fa46bfc75fb695b26326add22

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-4.8

before_install:
  - export CXX="g++-4.8"
  - npm install -g npm@latest
  - npm install -g ganache-cli
  - npm install -g truffle
  # Temporarily disabled as this bin has not been updated for Solc 5.0+
  # - npm install -g solidity-coverage

install:
  - npm install

before_script:
  - chmod +x ./scripts/test.sh
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run test
  # Temporarily disabled as this bin has not been updated for Solc 5.0+
  # - solidity-coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
